version: '3'

services: 
  front:
    build: 
      context: './frontend'
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    container_name: frontend_container
    networks:
      - mern-stack-network
    volumes:
      - ./react-docker:/app
    depends_on: 
      - backend
  
  backend:
    build:
      context: './backend' 
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    container_name: back
    networks:
      - mern-stack-network
    volumes:
      - ./express-docker:/app
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    container_name: mongo-container
    networks: 
      - mern-stack-network
    volumes: 
      - mongoData:/data/db
    env_file: ./config.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE 
    
networks:
  mern-stack-network:
volumes:  
  mongoData:



